{
 "title": "Keenetic",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "alias": "Ethernet Clients",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ip hotspot",
     "query": "SELECT last(\"speed\") as \"Ethernet\" FROM \"ip hotspot\" WHERE \"time\" > now() - 1m AND \"active\" = 1 AND $timeFilter GROUP BY \"mac\"",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "active", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Wi-Fi Clients",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"signal\") as \"Wi-Fi\" FROM \"ip hotspot\"  WHERE  \"time\" > now() - 1m AND \"active\" = 1 AND $timeFilter GROUP BY \"mac\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(\"uptime\") FROM \"system\" LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ByFly",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"rxspeed\"), last(\"txspeed\") FROM \"interface stat\" WHERE (\"name\"::tag = 'PPPoE1')  LIMIT 1"
    }
   ]
  },
  {
   "title": "Amigo",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"rxspeed\"), last(\"txspeed\") FROM \"interface stat\" WHERE (\"name\"::tag = 'PPPoE0')  LIMIT 1"
    }
   ]
  },
  {
   "title": "OpenVPN",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"rxspeed\"), last(\"txspeed\") FROM \"interface stat\" WHERE (\"name\"::tag = 'OpenVPN0')  LIMIT 1"
    }
   ]
  },
  {
   "title": "Wireguard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"rxspeed\"), last(\"txspeed\") FROM \"interface stat\" WHERE (\"name\"::tag = 'Wireguard0')  LIMIT 1"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "interface-name" ], "type": "tag" },
      { "params": [ "address" ], "type": "tag" },
      { "params": [ "description" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "interface",
     "query": "SELECT  last(\"state\") as \"State\" FROM \"interface\" GROUP BY \"description\"",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Internet status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "internet status",
     "query": "SELECT last(\"internet\") as \"Internet\", last(\"dns-accessible\") as \"DNS\", last(\"gateway-accessible\") as \"Gateway\" FROM \"internet status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "internet" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (mean(\"memtotal\") - mean(\"memfree\") - mean(\"membuffers\") - mean(\"memcache\")) as \"RAM Usage\" FROM \"system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"cpuload\") as \"CPU Usage\" FROM \"system\" Limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"cpuload\") as \"CPU Usage\" FROM \"system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpuload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"memtotal\") - mean(\"memfree\") FROM \"system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total",
     "query": "SELECT mean(\"memtotal\") FROM \"system\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "query": "SELECT(mean(\"rxspeed\")) FROM \"interface stat\" WHERE $timeFilter GROUP BY time($__interval), \"name\" fill(null)"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "query": "SELECT(mean(\"txspeed\")) FROM \"interface stat\" WHERE $timeFilter GROUP BY time($__interval), \"name\" fill(null)"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ip hotspot",
       "query": "SELECT non_negative_difference(mean(\"rxbytes\")) + non_negative_difference(mean(\"txbytes\")) FROM \"ip hotspot\" WHERE $timeFilter AND \"active\" = 1 GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "rxbytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ],
        [
         { "params": [ "txbytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "active", "operator": "=", "value": "True" }
       ]
      }
     ]
    },
    {
     "title": "Data usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ip hotspot",
       "query": "SELECT non_negative_difference(mean(\"sumspeed\")) FROM \"autogen\".\"ip hotspot\" WHERE $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "rxbytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ],
        [
         { "params": [ "txbytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "active", "operator": "=", "value": "True" }
       ]
      }
     ]
    },
    {
     "title": "Download data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "Download - $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_difference(mean(\"rxbytes\")) FROM \"interface stat\" WHERE $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Upload data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "interface stat",
       "query": "SELECT non_negative_difference(mean(\"txbytes\")) FROM \"interface stat\" WHERE $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "txbytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Scrape duration",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "alias": "$tag_command",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "command" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "collector",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "table",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "processes",
       "query": "SELECT mean(\"cpu\") AS \"CPU\", mean(\"memory\") AS \"RAM\" FROM \"processes\" WHERE $timeFilter GROUP BY \"name\"",
       "select": [
        [
         { "params": [ "cpu" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CPU" ], "type": "alias" }
        ],
        [
         { "params": [ "memory" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RAM" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Free media space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_label",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "label" ], "type": "tag" },
        { "params": [ "uuid" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "media",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}